--1. Tính Rookie Bonus:
WITH ROOKIE_TABLE AS (
SELECT * FROM [DPO].[BSP_TAN_INDIVIDUAL_KPI]
WHERE Period = 202401 AND Rookie <> '')

SELECT *,
CASE WHEN 
Rookie = 30 AND ( CAST(REPLACE(CC,'.','') AS INT) >= 1 AND CAST(REPLACE(CC,'.','') AS INT) <2 ) AND (CAST(REPLACE(FYP, '.0','') AS FLOAT) >= 15000000 AND CAST(REPLACE(FYP, '.0','') AS FLOAT) < 30000000) THEN 1
WHEN 
Rookie = 60 AND (CAST(REPLACE(CC,'.','') AS INT) >= 2 AND CAST(REPLACE(CC,'.','') AS INT) <3 ) AND (CAST(REPLACE(FYP, '.0','') AS FLOAT) >= 30000000 AND CAST(REPLACE(FYP, '.0','') AS FLOAT) < 45000000) THEN 2
WHEN 
Rookie = 90 AND (CAST(REPLACE(CC,'.','') AS INT) >=3) AND (CAST(REPLACE(FYP, '.0','') AS FLOAT) >= 45000000) THEN 3
ELSE 0 END AS Monthly_BONUS
FROM ROOKIE_TABLE
ORDER BY Monthly_BONUS desc